// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrGs1Lyz8F6sPqaQnIS2k68WGNb50-l-I',
    appId: '1:847356140861:web:72a6cd8c67d31639e6b954',
    messagingSenderId: '847356140861',
    projectId: 'savingsjarapp-7ad64',
    authDomain: 'savingsjarapp-7ad64.firebaseapp.com',
    storageBucket: 'savingsjarapp-7ad64.firebasestorage.app',
    measurementId: 'G-DS5TC9GWDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjSyuSCUTWdMxVMRPqkwlRQhCQoq6FpXA',
    appId: '1:847356140861:android:45b692907dc733f2e6b954',
    messagingSenderId: '847356140861',
    projectId: 'savingsjarapp-7ad64',
    storageBucket: 'savingsjarapp-7ad64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIvdUwt1nwCFvrJhw3MBA00UXsp-NCJfE',
    appId: '1:847356140861:ios:5867b638fe5bc8d5e6b954',
    messagingSenderId: '847356140861',
    projectId: 'savingsjarapp-7ad64',
    storageBucket: 'savingsjarapp-7ad64.firebasestorage.app',
    iosBundleId: 'com.example.savings',
  );
}
